import 'package:internpath/data/firebase/firebase_experience_service.dart';
import 'package:internpath/data/models/experience_model.dart';
import 'package:internpath/domain/entities/experience.dart';
import 'package:internpath/domain/repositories/experience_repository.dart';

class ExperienceRepositoryImpl extends ExperienceRepository {
  final FirebaseExperienceService _firebaseService;

  ExperienceRepositoryImpl(this._firebaseService);

  @override
  Future<Experience?> getExperienceById(String id) async {
    final data = await _firebaseService.getById(id);
    if (data == null) return null;
    return data.toEntity();
  }

  @override
  Future<List<Experience>> getExperiencesByUserId(
    String userId, {
    int limit = 10,
    Experience? lastExperience,
  }) async {
    final dataList = await _firebaseService.getByUserId(
      userId,
      limit: limit,
      lastExperience: lastExperience != null
          ? ExperienceModel.fromEntity(lastExperience)
          : null,
    );
    return dataList.map((data) => data.toEntity()).toList();
  }

  @override
  Future<List<Experience>> getExperiencesByCompanyId(
    String companyId, {
    int limit = 10,
    Experience? lastExperience,
  }) async {
    final dataList = await _firebaseService.getByCompanyId(
      companyId,
      limit: limit,
      lastExperience: lastExperience != null
          ? ExperienceModel.fromEntity(lastExperience)
          : null,
    );
    return dataList.map((data) => data.toEntity()).toList();
  }

  @override
  Future<List<Experience>> getAllExperiences({
    required String excludeUserId,
    int limit = 10,
    Experience? lastExperience,
  }) async {
    final dataList = await _firebaseService.getAllExperiences(
      excludeUserId: excludeUserId,
      limit: limit,
      lastExperience: lastExperience != null
          ? ExperienceModel.fromEntity(lastExperience)
          : null,
    );
    return dataList.map((data) => data.toEntity()).toList();
  }

  @override
  Future<void> addExperience(String userId, Experience experience) async {
    final model = ExperienceModel(
      id: '', // ID will be generated by Firestore
      companyId: experience.companyId,
      positionTitle: experience.positionTitle,
      salary: experience.salary,
      startDate: experience.startDate,
      endDate: experience.endDate,
      userId: userId,
      flexSchedule: experience.flexSchedule,
      continueOption: experience.continueOption,
      description: experience.description,
    );
    await _firebaseService.create(userId, model.toMap());
  }

  @override
  Future<void> updateExperience(
    String userId,
    String experienceId,
    Experience experience,
  ) async {
    final model = ExperienceModel(
      id: experienceId,
      companyId: experience.companyId,
      positionTitle: experience.positionTitle,
      salary: experience.salary,
      startDate: experience.startDate,
      endDate: experience.endDate,
      userId: userId,
      flexSchedule: experience.flexSchedule,
      continueOption: experience.continueOption,
      description: experience.description,
    );
    await _firebaseService.update(userId, experienceId, model.toMap());
  }

  @override
  Future<void> deleteExperience(String userId, String experienceId) async {
    await _firebaseService.delete(userId, experienceId);
  }
}
