import 'package:internpath/data/firebase/firebase_experience_service.dart';
import 'package:internpath/data/models/experience_model.dart';
import 'package:internpath/domain/entities/experience.dart';
import 'package:internpath/domain/repositories/experience_repository.dart';

class ExperienceRepositoryImpl extends ExperienceRepository {
  final FirebaseExperienceService _firebaseService;

  ExperienceRepositoryImpl(this._firebaseService);

  @override
  Future<Experience?> getExperienceById(String id) async {
    final data = await _firebaseService.getById(id);
    if (data == null) return null;
    return data.toEntity();
  }

  @override
  Future<List<Experience>> getExperiencesByUserId(
    String userId, {
    int limit = 10,
    Experience? lastExperience,
  }) async {
    final dataList = await _firebaseService.getByUserId(
      userId,
      limit: limit,
      lastExperience: lastExperience != null
          ? ExperienceModel.fromEntity(lastExperience)
          : null,
    );
    return dataList.map((data) => data.toEntity()).toList();
  }

  @override
  Future<List<Experience>> getExperiencesByCompanyId(
    String companyId, {
    int limit = 10,
    Experience? lastExperience,
  }) async {
    final dataList = await _firebaseService.getByCompanyId(
      companyId,
      limit: limit,
      lastExperience: lastExperience != null
          ? ExperienceModel.fromEntity(lastExperience)
          : null,
    );
    return dataList.map((data) => data.toEntity()).toList();
  }

  @override
  Future<List<Experience>> getAllExperiences({
    required String excludeUserId,
    int limit = 10,
    Experience? lastExperience,
  }) async {
    final dataList = await _firebaseService.getAllExperiences(
      excludeUserId: excludeUserId,
      limit: limit,
      lastExperience: lastExperience != null
          ? ExperienceModel.fromEntity(lastExperience)
          : null,
    );
    return dataList.map((data) => data.toEntity()).toList();
  }

  @override
  Future<String> addExperience(String userId, Experience experience) async {
    final model = ExperienceModel(
      id: '', // ID will be generated by Firestore
      companyId: experience.companyId,
      positionTitle: experience.positionTitle,
      salary: experience.salary,
      startDate: experience.startDate,
      endDate: experience.endDate,
      userId: userId,
      flexSchedule: experience.flexSchedule,
      continueOption: experience.continueOption,
      description: experience.description,
    );
    final experienceId = await _firebaseService.create(userId, model.toMap());
    return experienceId;
  }

  @override
  Future<void> updateExperience(
    String userId,
    String experienceId,
    Experience experience,
  ) async {
    final model = ExperienceModel(
      id: experienceId,
      companyId: experience.companyId,
      positionTitle: experience.positionTitle,
      salary: experience.salary,
      startDate: experience.startDate,
      endDate: experience.endDate,
      userId: userId,
      flexSchedule: experience.flexSchedule,
      continueOption: experience.continueOption,
      description: experience.description,
    );
    await _firebaseService.update(userId, experienceId, model.toMap());
  }

  @override
  Future<void> deleteExperience(String userId, String experienceId) async {
    await _firebaseService.delete(userId, experienceId);
  }

  // NUEVO: Implementación de búsqueda (fallback en cliente)
  // Nota: Firestore no soporta búsquedas por substring de forma nativa.
  // Aquí se obtiene un conjunto amplio de experiencias y se filtra localmente
  // por positionTitle y description (case-insensitive). Si quieres búsqueda
  // por nombre de empresa también, podemos hacer una segunda consulta a companies
  // y filtrar por el nombre (se puede añadir).
  @override
  Future<List<Experience>> searchExperiences(
    String userId,
    String query, {
    int limit = 50,
  }) async {
    final q = query.trim().toLowerCase();
    if (q.isEmpty) return [];

    // Traer un conjunto amplio (ajusta el límite si tu colección es grande)
    final fetchLimit = 500; // máximo a traer para filtrar localmente
    final dataList = await _firebaseService.getAllExperiences(
      excludeUserId:
          userId, // no excluir por defecto; se puede ajustar si hace falta
      limit: fetchLimit,
      lastExperience: null,
    );

    final all = dataList.map((d) => d.toEntity()).toList();

    final filtered = all.where((e) {
      final title = e.positionTitle.toLowerCase();
      final desc = (e.description ?? '').toLowerCase();
      return title.contains(q) || desc.contains(q);
    }).toList();

    if (filtered.length > limit) return filtered.sublist(0, limit);
    return filtered;
  }
}
