// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDm90OC_jgDZgwvgAtacZJCFjRyPw84WaQ',
    appId: '1:525551713767:web:0cd244e932bc9e95431142',
    messagingSenderId: '525551713767',
    projectId: 'internpath-23cba',
    authDomain: 'internpath-23cba.firebaseapp.com',
    storageBucket: 'internpath-23cba.firebasestorage.app',
    measurementId: 'G-HXJR4NRTD2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAsxYGSJx1_gamlZDi9b8DJ_bI8t-onKk',
    appId: '1:525551713767:android:a17a612a2235d2f5431142',
    messagingSenderId: '525551713767',
    projectId: 'internpath-23cba',
    storageBucket: 'internpath-23cba.firebasestorage.app',
  );

}